import '../models/goods_plan.dart';
import '../models/assessment.dart';

class DefaultTemplates {
  static List<GoodsPlan> getTraditionalTemplates() {
    return [
      GoodsPlan(
        id: 'template_1',
        name: '春联',
        category: '装饰用品',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1人',
          manpowerDetail: '需要1人负责挑选和购买，约需1-2小时',
          physical: '占用空间小',
          physicalDetail: '春联体积小，便于携带和存储，可放在抽屉或收纳盒中',
          financial: '50-200元',
          financialDetail: '根据材质和尺寸不同，普通纸质春联约50-100元，高档丝绸或金箔春联约100-200元',
          detailDescription: '春联是春节期间必不可少的装饰品，寓意着新的一年红红火火、吉祥如意。建议在腊月二十三至腊月二十九之间购买，选择寓意吉祥、字体工整的春联。',
        ),
        createdAt: DateTime.now(),
      ),
      GoodsPlan(
        id: 'template_2',
        name: '灯笼',
        category: '装饰用品',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1-2人',
          manpowerDetail: '需要1-2人负责挑选和购买，约需2-3小时，安装需要2人配合',
          physical: '占用空间中等',
          physicalDetail: '灯笼体积较大，需要预留存放空间，建议购买可折叠式灯笼便于收纳',
          financial: '100-500元',
          financialDetail: '普通纸灯笼约100-200元，LED灯笼约200-300元，大型装饰灯笼约300-500元',
          detailDescription: '灯笼象征着团圆和光明，是春节装饰的重要元素。建议购买LED灯笼，既节能又安全。大门口可挂大红灯笼，室内可挂小灯笼营造氛围。',
        ),
        createdAt: DateTime.now(),
      ),
      GoodsPlan(
        id: 'template_3',
        name: '年糕',
        category: '食品',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1-2人',
          manpowerDetail: '购买需1人，约需1小时；自制需2-3人，约需半天',
          physical: '占用空间中等',
          physicalDetail: '年糕需要冷藏保存，占用冰箱空间，建议购买真空包装便于储存',
          financial: '50-300元',
          financialDetail: '购买成品年糕约50-100元，自制材料约100-200元，高档礼盒装年糕约200-300元',
          detailDescription: '年糕寓意"年年高升"，是春节传统食品。可根据家庭口味选择甜年糕或咸年糕，也可以购买不同口味的年糕满足家人需求。',
        ),
        createdAt: DateTime.now(),
      ),
      GoodsPlan(
        id: 'template_4',
        name: '糖果',
        category: '食品',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1人',
          manpowerDetail: '需要1人负责购买，约需1-2小时，需要仔细挑选种类和品牌',
          physical: '占用空间小',
          physicalDetail: '糖果体积小，便于收纳，建议使用密封罐或专用糖果盒保存',
          financial: '100-500元',
          financialDetail: '普通糖果约100-200元，进口糖果约200-300元，高档礼盒装约300-500元',
          detailDescription: '糖果是招待客人的必备食品，寓意生活甜甜蜜蜜。建议准备多种口味和品种，包括巧克力、软糖、硬糖等，满足不同年龄段的喜好。',
        ),
        createdAt: DateTime.now(),
      ),
      GoodsPlan(
        id: 'template_5',
        name: '坚果',
        category: '食品',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1人',
          manpowerDetail: '需要1人负责购买，约需1-2小时，需要挑选新鲜优质的坚果',
          physical: '占用空间小',
          physicalDetail: '坚果体积小，便于收纳，建议使用密封袋或专用坚果盒保存，防潮防虫',
          financial: '100-400元',
          financialDetail: '普通坚果约100-200元，进口坚果约200-300元，高档礼盒装约300-400元',
          detailDescription: '坚果寓意"硕果累累"，是春节待客的健康食品。建议准备瓜子、花生、核桃、开心果、杏仁等多种坚果，营养美味又健康。',
        ),
        createdAt: DateTime.now(),
      ),
      GoodsPlan(
        id: 'template_6',
        name: '红包',
        category: '礼品',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1人',
          manpowerDetail: '需要1人负责购买，约需30分钟-1小时，需要准备足够数量',
          physical: '占用空间小',
          physicalDetail: '红包体积小，便于收纳，建议使用专用收纳盒整理，避免丢失',
          financial: '50-200元',
          financialDetail: '普通红包约50-100元，高档烫金红包约100-150元，定制红包约150-200元',
          detailDescription: '红包是春节期间给晚辈和亲友的传统礼物，寓意着祝福和好运。建议根据需要准备不同规格和样式的红包，提前准备好现金以便随时使用。',
        ),
        createdAt: DateTime.now(),
      ),
      GoodsPlan(
        id: 'template_7',
        name: '烟花爆竹',
        category: '娱乐用品',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1-2人',
          manpowerDetail: '购买需1人，约需1小时；燃放需2-3人配合，注意安全',
          physical: '占用空间中等',
          physicalDetail: '烟花爆竹需要干燥通风的环境存放，远离火源和易燃物',
          financial: '200-1000元',
          financialDetail: '小型烟花约200-500元，中型烟花约500-800元，大型烟花约800-1000元',
          detailDescription: '烟花爆竹是春节庆祝活动的重要组成部分，寓意着辞旧迎新、驱邪避灾。购买时需选择正规渠道，燃放时注意安全，遵守当地规定。',
        ),
        createdAt: DateTime.now(),
      ),
      GoodsPlan(
        id: 'template_8',
        name: '新衣服',
        category: '服装',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1-2人',
          manpowerDetail: '需要1-2人负责购买，约需半天到一天，需要试穿和挑选',
          physical: '占用空间中等',
          physicalDetail: '新衣服需要悬挂或折叠存放，占用衣柜空间，建议提前整理衣柜',
          financial: '500-3000元',
          financialDetail: '普通新衣服约500-1000元，品牌服装约1000-2000元，高档定制约2000-3000元',
          detailDescription: '穿新衣服是春节传统习俗，寓意着新的开始和好运。建议提前购买，避免临近春节时商场拥挤，可选择红色或喜庆的颜色增添节日氛围。',
        ),
        createdAt: DateTime.now(),
      ),
      GoodsPlan(
        id: 'template_9',
        name: '水果',
        category: '食品',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1人',
          manpowerDetail: '需要1人负责购买，约需1-2小时，需要挑选新鲜水果',
          physical: '占用空间大',
          physicalDetail: '水果需要冷藏保存，占用冰箱空间，建议购买前清理冰箱空间',
          financial: '200-800元',
          financialDetail: '普通水果约200-400元，进口水果约400-600元，高档礼盒装约600-800元',
          detailDescription: '水果是春节待客和祭祀的重要食品，寓意着吉祥如意、平平安安。建议准备苹果、橘子、香蕉、葡萄等多种水果，既美观又健康。',
        ),
        createdAt: DateTime.now(),
      ),
      GoodsPlan(
        id: 'template_10',
        name: '酒水饮料',
        category: '食品',
        isCustom: false,
        targetDate: null,
        isCompleted: false,
        assessment: Assessment(
          manpower: '1人',
          manpowerDetail: '需要1人负责购买，约需1-2小时，需要根据家庭需求选购',
          physical: '占用空间中等',
          physicalDetail: '酒水饮料需要阴凉干燥的环境存放，占用储藏空间',
          financial: '300-1500元',
          financialDetail: '普通酒水约300-600元，中档酒水约600-1000元，高档酒水约1000-1500元',
          detailDescription: '酒水饮料是春节聚餐和待客的必备品，寓意着团圆和欢乐。建议准备白酒、红酒、啤酒、果汁等多种饮品，满足不同客人的需求。',
        ),
        createdAt: DateTime.now(),
      ),
    ];
  }

  static List<String> getCategories() {
    return [
      '装饰用品',
      '食品',
      '礼品',
      '娱乐用品',
      '服装',
      '其他',
    ];
  }
}